"""Yangi foydalanuvchilar uchun dastlabki (default) kalit so'zlar ro'yxati.

Bu ro'yxatlar mavjud ishlab chiqarish tajribasi asosida yig'ilgan va yangi ro'yxatdan o'tgan foydalanuvchilarga avtomatik qo'shiladi (foydalanuvchi keyinchalik o'zi tahrirlashi mumkin)."""

DEFAULT_PASSENGER_KEYWORDS = [
    'kerak',
    'ketish kerak',
    'olib keting',
    "yo'lovchi kerak",
    'borish kerak',
    'ketmoqchiman',
    '1 kishi bor',
    '1 kiwi bor',
    '1 ta odam bor',
    '1 киши бор',
    '1 та одам бор',
    '1ита одам бор',
    '2 kishi bor',
    '2 ta odam bor',
    '2 та одам бор',
    '2ta odam bor',
    '2та одам бор',
    '3 kishi bor',
    '3 ta odam bor',
    '3 та одам бор',
    '3ta odam bor',
    '4 kishi bor',
    '4 ta odam bor',
    '4 та одам бор',
    '5 ta odam bor',
    'assalomu aleykum xayrli kech hammaga ertaga toshkentdan chustga ketishga taksilar bormi',
    'bitta odam bor',
    'kamfort',
    'ketaman',
    'moshina kerak',
    'odam bor',
    'orqa salon',
    'pochta bor',
    'poshta',
    'poshta bor',
    'powta bor',
    'pustoy kerak',
    'sroshni taxi kerak',
    'taksi ketak',
    'taxi kerak',
    'ayol kishi',
    'bir kishi bor',
    'boraman',
    'borishim kerak',
    'kishi bor',
    'mashina',
    'mashina kerak',
    'mashina kk',
    'oldi mestaga odam bor',
    'olib ketishingiz',
    'taksi',
    'taksi kerak',
    'taksi kk',
    "yo'lovchi",
    'ассалому алейкум тошкентдан чустга 2 киши бор яанги йолдан',
    'аёл киши',
    'рошта бор',
    'айол кишига мошина керак',
    'битта одам бор',
    'кетаман',
    'мoshina kerak',
    'машина борми',
    'машина керак',
    'мошина борми',
    'мошина керак',
    'оdam bor',
    'одам бор',
    'олди местага одам бор',
    'орка салон',
    'орқа салон',
    'почта бор',
    'пустой',
    'салон',
    'такси борми',
    'такси керак',
    'kecha ertaga bugun nima qilish kerak',
    'men olaman odam kim ketadi',
    '3 ta kam',
    'bugun qaysi kun',
    'yuramiz',
]


DEFAULT_DRIVER_KEYWORDS = [
    'ketaman',
    'boraman',
    'olib ketaman',
    'haydovchiman',
    'mashina bor',
    'taksi',
    '1 ta kam',
    '2 ta kam',
    '3 ta kam',
    'avto cobalt',
    'almatov adhamjon olib yuramz',
    'benzin',
    'beraman',
    'beton ishi qilamiz apalifka',
    'biyagomis',
    'bolsa ham olamiz',
    'elektrik montajga',
    'gaz',
    'gisht',
    "g'ozapoya",
    'harakatdamiz',
    "ishonchli mega semichka urug'larbor t6 36 kg narxi 38 dollor urug'ga garantiya beramiz",
    'jiyanboy urugi bor ishonchlik',
    'kamdamiz',
    'kamdamiz камдамиз',
    'karam koʻchat',
    'kartoshka urugʻ sotiladigan',
    'kilyonka',
    'koʻchat',
    'kulok',
    'labo',
    'makka',
    'makka poya sotiladi',
    'mol savzi',
    'olaman',
    'olamiz',
    'oq gurbak uruq garantiylik',
    'oqlovya',
    'oqloʻvla',
    'osmon yonģoq',
    'pochta olamiz',
    'piyoz urugʻ sotaman',
    'poya',
    'premium',
    'qizil sabzi',
    'qovun',
    "qovun urug' kerak ishonchli koʻkcha bilan",
    'sabzi',
    'samon maydalagich aparat kimda kattasidan',
    'santa kartoshka',
    'semichka',
    'semichkadan',
    'sinamal obnovot urugʻ',
    'sotiladi',
    'tarvuz',
    'tarvuz koʻchat',
    'tarvuz kulok uchun tuproq',
    'tel qilib yuboring',
    'urugʻ',
    'xashak sotiladi',
    'xizmati',
    'yongoq pochoq sotiladi',
    'yuramiz',
    'yuryapmiz',
    'zaruri',
    'aksiya arzon narxlarda guruhizga juvoy qushiib beraman admiinla kimga kerak lichkamga yozing narxlarni tashlayman siiz aytgan viloyatdan qushib beraman',
    'arzon narxlarda guruhizga qushiib beramiz narxiini siiz aytasiz savdolashamiz lichkamga',
    'bolsa',
    'elab qoplangan tozza quruq biyogumis',
    'kam srochni yuramiz',
    'ketamiz',
    'kimda damazga zadnimos',
    'kimga',
    'lic',
    'olib',
    'pochta olib yuramz',
    'qayda bozor boladi biladiganla',
    'yozinglar',
    'билан',
    'билан кеторамиз',
    'билан кетамиз',
    'кетамиз',
    'новый год на носу',
    'нужно покосить траву у меня на даче',
    'оламиз',
    'олип кеторамиз',
    'олип авто',
    'олип юраммиз авто кобальт',
    'пустой',
    '2 ta odam poshta olamz',
    'tom bagaj bor',
    'migirim',
    'шу нумерда тошкент дан тошкургонда аёл кишиборлар тел килилар',
    'юрерамиз',
    'клент',
    'odam kerak',
    '1 kishi kerak',
    'kishi kerak',
    'poshta olamz',
    'mehr',
    'срочный',
    'srochni',
    'avto',
    'ertalabga 3ta odam bor moshina kerak',
    'ziyoratga moshina kerak',
    'учқўрғон уйчидан тошкентга соат 16 17:00га 2та одам камдамиз аёл киши бор',
    'тошкендан попга юрамиз 2 та кам аёл киши бор авто коблт',
    'namangandan toshkentga toldik yolimizda poshta bosa nemer',
    'киши кам',
    'kishi kam',
]
